### ISSUE TITLE
JSON columns not supported

### ISSUE THREAD

**Issue by ehuebner** [datamill-co/target-postgres#184] opened 2020-04-30 09:20 UTC
Hi,
i am using `tap-mysql` and `tap-postgresql` to sync database tables into `target-postgres`.
In both taps i have tables with the field type `JSON`. But on the target postgres table it is has field type `string` and i cannot query the fields inside anymore.

Is it intended to not support field type `JSON`? I know singer uses JSON Schema and that does not supported embedded JSON. Maybe JSON could be a custom string format?
[JSON Schema string formats](https://json-schema.org/understanding-json-schema/reference/string.html?highlight=format)
Or is there any other solution for that?

Thanks in advance.

**Comment by AlexanderMann** [comment] 2020-04-30 14:16
👋 Hey @ehuebner!

It's true that we currently do not support `JSON` types. There are a number of hurdles to this, one of which you mentioned: JSONSchema not having a type for this.

String formats have been thrown out as an option.

Out of curiosity, can you leverage `::JSON` JSON casting in Postgres to query these fields? That's how we're currently using this for similar data.

**Comment by ehuebner** [comment] 2020-05-04 14:57
Hi @AlexanderMann!
Your suggested method works quite well. Performance could become an issue since the strings are parsed per query and there are no indices. For a full table sync it would be possible to have a post sync process that changes the `JSON` fields like this:
`ALTER TABLE table1 ALTER COLUMN col1 TYPE JSON USING col1::JSON;`
This was mentioned here:
https://stackoverflow.com/questions/16074375/postgresql-9-2-convert-text-json-string-to-type-json-hstore

But the problem still exists: On the target side there is no way to identify what field was a `JSON` field on the tap side. 😕

**Comment by AlexanderMann** [comment] 2020-05-04 15:52
Yeah, there have been some conversations around how to add this programmatically based on the depth of parsing/denesting. But for a single field, it's tricky to have it consistently identify a single field as being needed to be parsed as JSON.

Would allowing `target-postgres` to throw everything after a certain depth of unnesting into a catchall JSONB column solve this problem for you, or is this really about a single field which _is_ a JSON string and unnesting that into JSONB?

**Comment by ehuebner** [comment] 2020-05-06 07:27
I have multiple tables with with each two (for this context interesting) fields:
`type` & `payload`
Type is basicly a name for a schema of the payload.
Payload is a JSON field. It can have different schemas in the same table.

So it is about single fields that could be transported as string but that need to be parsed to JSON on the target side again.

I was thinking about having some post sync process that checks all string fields for JSON values and runs the `ALTER COLUMN` command. But that is really brute force.

**Comment by AlexanderMann** [comment] 2020-05-06 15:58
Gotchya. Would a materialized view work? Also, `target-postgres` has post hooks which might work for you

**Comment by awm33** [comment] 2020-05-16 21:22
@ehuebner How do the fields come across in Singer? What are the JSON Schema types and what does the JSON object look like?

I'm assuming it's either coming across as either a:
1) JSON that is part of the record structure
2) Stringified JSON in a string typed field

**Comment by ehuebner** [comment] 2020-05-18 09:06
I use `tap-mysql`, `tap-postgres` & `target-postgres`.
Both taps are transforming a `JSON` field to a `string` stream.
@awm33 I was thinking a bit about having the `JSON` field as a part of the record structure. I do not know if this is really a good idea. We have different schemas in the same table field. That would mean the record structure is a mixture of different schemas. Bad idea. If you habe only rows with the same schema and you also maintain the schema in postgres to validate your insert statements based on that schema it would be a good idea.
I think using `string` type in the singer stream is the more resilient solution. Like mentioned the target side is missing the information that a field is a `JSON` and not just a `string`.

@AlexanderMann Can you give some additional words to your idea how a materialized view could solve the problem?

**Comment by AlexanderMann** [comment] 2020-05-18 15:20
@ehuebner I think something like this would work, but I'm not sure as to your setup etc.

```
CREATE VIEW as_json AS
    SELECT
        *,
        json_string_column::JSONB AS json_column
    FROM singer_target_postgres_table
```

**Comment by awm33** [comment] 2020-05-19 17:04
@ehuebner I think @AlexanderMann 's proposal is your best bet. In a view, your data modeling layer, or in a your queries, just cast the column to JSON.

At this point, it's a string, the tap choose that as the best representation, which it honestly might be. Without a schema declared it would be rejected by target-postgres anyway (we use the JSON schema to construct tables) and you can still use it as a JSON column in the destination.

**Comment by awm33** [comment] 2020-07-08 21:15
I'm closing this out since this is really more if an issue with the tap, and the tap emits postgres JSON as string by design.

**Closed by awm33** 2020-07-08 21:15 UTC
