### ISSUE TITLE
ValidationError: '296.91 is not a multiple of 0.01'

### ISSUE THREAD

**Issue by ehuebner** [datamill-co/target-postgres#181] opened 2020-04-06 14:35 UTC
Hi, i use `tap-mysql` to `target-postgre` and get following error for `DECIMAL` fields:

`target_postgres.exceptions.SingerStreamError: ('Invalid records detected above threshold: 0. See `.args` for details.', [(<ValidationError: '296.91 is not a multiple of 0.01'>, {'type': 'RECORD', 'stream': 'stream', 'record': {'field1': None, 'field2': 296.91, field3': False, 'field4': '2019-11-13T07:51:30.000000Z', 'field5': 3241, field6': 'c2fea17b-b93d-4f9c-80e6-f0b430bd7641', 'field7': None, 'field8': 'canceled', 'field9': 49900.0, 'field10': None, 'field11': None, 'field12': 'bb49d636-39eb-45ba-a2d7-1d899e0f64b2', 'field13': 'df0cf32b-3c74-4423-9776-abaa0b9619f3', 'field14': False, 'field15': '2019-11-17T07:51:30.000000Z', 'field16': 'f38dbaae-3a8b-46d2-84d1-365cfea5a22c', 'field17': False, 'field18': '2020-02-10T15:10:20.000000Z', 'field19': '2019-12-04T12:00:00.000000Z', 'field20': 'bcad5133-e571-4d87-a8be-ff3bd521030b', 'field21': 249.5, 'field22': None, 'field23': '2019-11-14T12:00:00.000000Z', 'field24': 80263, 'field25': '00d158bb-2b79-46f9-8aec-aa62c32b6440', 'field26': None}, 'version': 1586182324138, 'time_extracted': '2020-04-06T14:12:04.821434Z', '__raw_line_size': 1231})])`

**Comment by AlexanderMann** [comment] 2020-04-06 14:51
This is a duplicate of #178

**Closed by AlexanderMann** 2020-04-06 14:51 UTC

**Comment by AlexanderMann** [comment] 2020-04-06 14:53
For the record, we have a fix here for this, but have yet to deploy it. This should up the urgency for this.
